# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mike Mackintosh
tagline:          Cybertube Home of Mike Mackintosh
url:              http://www.mikemackintosh.com
paginate:         1
baseurl:          /
author:
  name:           Mike Mackintosh
  url:            https://twitter.com/mikemackintosh
  ghurl:          https://github.com/mikemackintosh
  email:          mike@rocketho.me