# Permalinks
permalink: pretty
production_url : http://www.mikemackintosh.com
#relative_permalinks: true
markdown: redcarpet
highlighter: pygments
extensions: [fenced_code_blocks]
redirects: yes

# Setup
title:            Mike Mackintosh
tagline:          and some of the really cool shit that i've done
url:              http://www.mikemackintosh.com
paginate:         20
baseurl:          /
author:
  name:           Mike Mackintosh
  url:            https://twitter.com/mikemackintosh
  ghurl:          https://github.com/mikemackintosh
  email:          mike@rocketho.me
ASSET_PATH: /public/